version: '2'
services:
    cvtheque-app:
        image: cvtheque
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://cvtheque-postgresql:5432/cvtheque
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=cvtheque-elasticsearch:9300
        ports:
            - 8080:8080
    cvtheque-postgresql:
        extends:
            file: postgresql.yml
            service: cvtheque-postgresql
    cvtheque-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: cvtheque-elasticsearch
